### ISSUE TITLE
Use of Http local API for Buderus KM200

### ISSUE THREAD

**Issue by moustic999** [marconfus/aionefit#1]
Dear,

Buderus KM200 is a gateway for internet communication for buderus heating system. It woks via Xmpp and bosch servers. However there is also a local http api which can be used. Fhem, openhab make use of this local API.
I began myself to try writing python to support it but lack of time and python knowledge blocks me to progress.
As it is now code is working but should be expanded to support all feature, basically add support of all api endpoints 
here is the link : https://github.com/moustic999/buderus-client-python

**Comment by marconfus** [comment]
Hi,

unfortunately the thermostat I have (Junkers CT100) doesn't have a local webserver. It seems that you can only talk to it via the Bosch server. I dont's think there is real benefit in trying to support both channels (HTTP and XMPP) in one library. Also your code looks quite good.
