### ISSUE TITLE
add auto-discovery for Thermostat

### ISSUE THREAD

**Issue by moustic999** [marconfus/aionefit#2]
while reverse-engineering the buderus app, I found that there is a mDNS inside which look for 'iCom' device
I made pull request to enable it in netdisco 
https://github.com/home-assistant/netdisco/pull/223
It is not yet accepted as this is very generic.
A good idea would be to check if this mDns also exists on nefit and bosch device, in order to enable on all devices.

**Comment by marconfus** [comment]
As the device I'm targeting has no local webserver, there is also no mDNS propagating it...
